Null Hypothesis (H₀): The male-female buyer ratios are not similar across all regions (Independent).

Alternative Hypothesis (H₁): The male-female buyer ratios are similar across all regions (dependent).

We are going to conduct a Chi-Square test of Independence with Contingency table

In [14]:
import pandas as pd
df = pd.read_csv("C:\\Users\\marpaka pradeep sai\\Downloads\\BuyerRatio.csv")
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [15]:
import numpy as np
from scipy.stats import chi2_contingency

In [16]:
# Given data
observed_values = np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])
print(observed_values)

[[  50  142  131   70]
 [ 435 1523 1356  750]]


In [17]:
# Perform chi-square test
chi2, p, dof, expected = chi2_contingency(observed_values)

In [18]:
print("Chi-square value :", chi2)

Chi-square value : 1.595945538661058


In [19]:
print("P value :", p)

P value : 0.6603094907091882


In [20]:
P_value = p

In [21]:
print("Degrees of Freedom :", dof)

Degrees of Freedom : 3


In [22]:
print("Expected values :",expected)

Expected values : [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [23]:
# 5% level of significance
alpha = 0.05

In [24]:
if P_value < alpha:
    print("H0 is rejected and H1 is accepted")
    print("Therefore, there is a significance evidence to conclude that the male-female buyer ratios are similar across all regions.")
else :
    print("H1 is rejected and H0 is accepted")
    print("Therefore, there is a significance evidence to conclude that the male-female buyer ratios are not similar across all regions.")
    

H1 is rejected and H0 is accepted
Therefore, there is a significance evidence to conclude that the male-female buyer ratios are not similar across all regions.


# Therefore, there is a significance evidence to conclude that the male-female buyer ratios are not similar across all regions.Hence, the male-female buyer ratio is independent across different regions.